import type { CohnReznickAnalysis } from "@/types/analysis";

export const SAMPLE_ANALYSIS: CohnReznickAnalysis = {
  data_summary: {
    period_range: "Jan 2021 – Dec 2023",
    total_months: 36,
    accounts_processed: 142,
    total_entries: 4284,
    files_ingested: ["Meridian_TB_2021-2023.xlsx", "Meridian_Workpapers_Q3Q4_2023.docx"],
    account_categories: ["Revenue", "COGS", "SG&A", "Payroll", "Accounts Receivable", "Inventory", "Fixed Assets", "Debt"],
  },
  anomaly_findings: [
    {
      finding_id: "ANO-001",
      account_name: "Payroll Expense",
      account_code: "6100",
      period: "Jul 2023 – Sep 2023",
      movement_type: "Spike",
      delta_absolute: 1420000,
      delta_percentage: 34.2,
      severity: "Critical",
      source_reference: "Meridian_TB_2021-2023.xlsx, Sheet 'P&L', Row 47",
      description: "Payroll expense surged $1.42M (34%) in Q3 2023 vs Q2 2023 without corresponding headcount additions in workpapers. Possible accrual adjustments, bonuses, or reclassification from COGS.",
      call_to_action: {
        title: "Request Payroll Reconciliation for Q3 2023",
        description: "Payroll Expense (6100) increased $1.42M in Q3 2023 with no supporting headcount documentation. Obtain payroll register, bonus payout schedule, and HR headcount reports for Jul–Sep 2023.",
        impact: "If unresolved, this anomaly inflates normalised EBITDA by approximately $1.4M, materially affecting valuation multiples.",
        action_when_approved: [
          "Add issue ANO-001 to the Issue Tracker as Critical — open",
          "Generate management question: 'Please provide payroll register and bonus schedule for Jul–Sep 2023 reconciling to the $1.42M increase in account 6100.'",
          "Flag for inclusion in diligence report Section 3.2 — Payroll Normalisation",
        ],
        action_when_rejected: [
          "Mark finding ANO-001 as reviewed and dismissed",
          "Log analyst note: 'Payroll spike attributed to one-time restructuring charge per management — no further action required.'",
        ],
        suggestion_prompt: "Draft a management follow-up question requesting payroll register and bonus payout details for Q3 2023 to reconcile the $1.42M spike in account 6100.",
        target_recipient: "CFO / VP Finance — Meridian Industrial Solutions",
        target_channel: "Question List",
        priority: "Critical",
        status: "Pending",
      },
    },
    {
      finding_id: "ANO-002",
      account_name: "Accounts Receivable",
      account_code: "1200",
      period: "Oct 2023 – Dec 2023",
      movement_type: "Build-Up",
      delta_absolute: 4200000,
      delta_percentage: 28.6,
      severity: "High",
      source_reference: "Meridian_TB_2021-2023.xlsx, Sheet 'Balance Sheet', Row 12",
      description: "Accounts receivable grew $4.2M (29%) over Q4 2023 with no corresponding revenue growth. Aging schedule not provided in workpapers. Collectability risk and potential revenue pull-forward.",
      call_to_action: {
        title: "Request AR Aging Schedule and Customer Concentration Analysis",
        description: "AR balance increased $4.2M in Q4 2023 while revenue was flat. Obtain AR aging schedule, top-10 customer breakdown, and any recent bad-debt write-offs.",
        impact: "Inflated AR may indicate channel stuffing or collection issues. Could reduce normalised working capital by $2–4M depending on collectability.",
        action_when_approved: [
          "Add issue ANO-002 to Issue Tracker as High — open",
          "Generate management question: 'Please provide AR aging schedule as of Dec 31, 2023 and identify any balances >90 days or disputed.'",
          "Include in working capital analysis — flag for Section 4.1 of diligence report",
        ],
        action_when_rejected: [
          "Mark finding ANO-002 as reviewed — management confirms timing difference from large Q4 sale",
          "Log note: 'AR build-up attributed to $4.2M sale to ABC Corp on Dec 28 — collected Jan 15, 2024.'",
        ],
        suggestion_prompt: "Request AR aging schedule and customer concentration analysis from management to assess collectability of Q4 2023 AR build-up.",
        target_recipient: "Controller — Meridian Industrial Solutions",
        target_channel: "Question List",
        priority: "High",
        status: "Pending",
      },
    },
    {
      finding_id: "ANO-003",
      account_name: "Cost of Goods Sold",
      account_code: "5000",
      period: "Nov 2023 – Dec 2023",
      movement_type: "Spike",
      delta_absolute: 870000,
      delta_percentage: 22.1,
      severity: "High",
      source_reference: "Meridian_TB_2021-2023.xlsx, Sheet 'P&L', Row 28",
      description: "COGS increased $870K in Nov–Dec 2023 while revenue was flat, compressing gross margin from 38% to 29%. No purchase order or inventory build noted in workpapers.",
      call_to_action: {
        title: "Investigate COGS Spike and Gross Margin Compression",
        description: "COGS rose $870K in Q4 2023 with flat revenue, compressing gross margins by 9 percentage points. Request purchase orders, inventory movement, and vendor invoices for Nov–Dec 2023.",
        impact: "Normalised gross margin impact of ~$870K. If structural, this reduces LTM EBITDA by approximately $870K and warrants a quality-of-earnings adjustment.",
        action_when_approved: [
          "Add issue ANO-003 to Issue Tracker as High — open",
          "Generate management question: 'Please explain the COGS increase of $870K in Nov–Dec 2023 and provide supporting purchase orders and vendor invoices.'",
          "Include QoE adjustment in report Section 2.4 — COGS Normalisation",
        ],
        action_when_rejected: [
          "Mark finding ANO-003 as reviewed — confirmed one-time bulk purchase",
          "Log note: 'COGS spike attributed to strategic raw material pre-buy ahead of announced tariff increase — non-recurring.'",
        ],
        suggestion_prompt: "Draft a question requesting purchase orders and vendor invoices for the COGS spike in Nov–Dec 2023 to assess whether it is recurring or non-recurring.",
        target_recipient: "VP Operations — Meridian Industrial Solutions",
        target_channel: "Question List",
        priority: "High",
        status: "Pending",
      },
    },
    {
      finding_id: "ANO-004",
      account_name: "Other Income",
      account_code: "7800",
      period: "Mar 2023",
      movement_type: "One-Time Credit",
      delta_absolute: 650000,
      delta_percentage: 100,
      severity: "Medium",
      source_reference: "Meridian_TB_2021-2023.xlsx, Sheet 'P&L', Row 78",
      description: "A $650K credit appeared in Other Income in March 2023 with no prior activity in this account. Likely a non-recurring gain — insurance settlement, asset sale, or reclassification.",
      call_to_action: {
        title: "Identify Nature of $650K Other Income Credit",
        description: "A one-time $650K credit in account 7800 (Other Income) in Mar 2023 with no prior history. Must be classified as non-recurring for EBITDA normalisation.",
        impact: "If non-recurring (likely), this reduces normalised LTM EBITDA by $650K and must be excluded from the adjusted earnings base.",
        action_when_approved: [
          "Add issue ANO-004 to Issue Tracker as Medium — open",
          "Generate management question: 'Please identify the source of the $650K credit in account 7800 in March 2023 and provide supporting documentation.'",
          "Pre-classify as non-recurring QoE adjustment pending management confirmation",
        ],
        action_when_rejected: [
          "Mark finding ANO-004 as reviewed — confirmed recurring consulting income",
          "Log note: 'Other Income confirmed as recurring consulting retainer — retain in normalised EBITDA.'",
        ],
        suggestion_prompt: "Ask management to identify and document the source of the $650K credit in Other Income (account 7800) in March 2023.",
        target_recipient: "CFO — Meridian Industrial Solutions",
        target_channel: "Question List",
        priority: "Medium",
        status: "Pending",
      },
    },
  ],
  driver_analysis: [
    {
      driver_id: "DRV-001",
      linked_finding_id: "ANO-001",
      root_cause: "Potential one-time bonus accrual or payroll reclassification from COGS to SG&A in Q3 2023. Correlation with a simultaneous $420K decrease in direct labour costs (account 6050) suggests an internal reclassification event.",
      supporting_evidence: "Account 6050 (Direct Labour) decreased $420K in the same period. No new hire documentation in workpapers. Payroll run dates match period-end accrual entries.",
      cross_referenced_accounts: ["6050 — Direct Labour", "6100 — Payroll Expense", "2300 — Accrued Liabilities"],
      confidence: "Medium",
      call_to_action: {
        title: "Confirm Reclassification from Direct Labour to Payroll Expense",
        description: "Evidence points to a reclassification of $420K from account 6050 to 6100 in Q3 2023. Validate with journal entry detail and payroll mapping documentation.",
        impact: "If confirmed as a reclassification, the net EBITDA impact is limited to the residual $1.0M — reducing the initial anomaly severity but still requiring normalisation.",
        action_when_approved: [
          "Request journal entry detail for accounts 6050 and 6100 in Q3 2023",
          "Link driver DRV-001 to issue ANO-001 in Issue Tracker",
          "Adjust QoE workpaper to reflect partial reclassification offset",
        ],
        action_when_rejected: [
          "Mark driver DRV-001 as unconfirmed — treat full $1.42M as unexplained",
          "Escalate ANO-001 to senior review given unresolved driver",
        ],
        suggestion_prompt: "Request journal entry detail for accounts 6050 and 6100 in Q3 2023 to confirm or deny the reclassification hypothesis.",
        target_recipient: "Controller — Meridian Industrial Solutions",
        target_channel: "Question List",
        priority: "High",
        status: "Pending",
      },
    },
    {
      driver_id: "DRV-002",
      linked_finding_id: "ANO-002",
      root_cause: "Large Q4 2023 sale to a single customer (estimated >$4M) with extended payment terms, or revenue pull-forward ahead of year-end. Historical AR DSO of 28 days has increased to 51 days in Q4 2023.",
      supporting_evidence: "Revenue remained flat QoQ despite AR build-up. DSO calculation from TB data shows 51-day DSO vs 28-day historical average. No new customer contract disclosed in workpapers.",
      cross_referenced_accounts: ["4000 — Net Revenue", "1200 — Accounts Receivable", "1210 — Allowance for Doubtful Accounts"],
      confidence: "High",
      call_to_action: {
        title: "Validate DSO Increase and Customer Payment Terms",
        description: "AR DSO increased from 28 to 51 days in Q4 2023. Obtain customer contract for the large Q4 sale and confirm payment receipt date to determine if collection risk exists.",
        impact: "If AR of $4.2M is not collected within normal terms, the working capital target in the purchase agreement may need adjustment of $1–2M.",
        action_when_approved: [
          "Request top-customer AR aging detail and any extended payment agreements signed in Q4 2023",
          "Calculate normalised DSO adjustment for working capital peg",
          "Link DRV-002 to ANO-002 in Issue Tracker",
        ],
        action_when_rejected: [
          "Mark DRV-002 as resolved — management confirms Q4 AR collected in Jan 2024",
          "Remove AR build-up from working capital normalisation adjustments",
        ],
        suggestion_prompt: "Request AR aging detail and the customer contract for the largest Q4 2023 receivable to assess collectability and DSO normalisation.",
        target_recipient: "Controller — Meridian Industrial Solutions",
        target_channel: "Question List",
        priority: "High",
        status: "Pending",
      },
    },
  ],
  follow_up_questions: [
    {
      question_id: "FUQ-001",
      question_text: "Please provide a complete payroll register and bonus payout schedule for July – September 2023 reconciling to the $1.42M increase in Payroll Expense (account 6100). Include headcount by month and any one-time compensation items.",
      priority: "Critical",
      target_audience: "CFO / VP Finance",
      linked_finding_id: "ANO-001",
      rationale: "A $1.42M payroll spike without documented headcount changes is a primary QoE risk. Management's explanation will determine whether an EBITDA normalisation adjustment is required.",
      call_to_action: {
        title: "Send FUQ-001 to CFO / VP Finance",
        description: "Deliver question FUQ-001 requesting payroll register and bonus schedule for Q3 2023 to reconcile the $1.42M payroll expense spike.",
        impact: "Unresolved, this question blocks finalisation of EBITDA normalisation for the diligence report.",
        action_when_approved: [
          "Add FUQ-001 to the management question list deliverable",
          "Set response deadline of 5 business days",
          "Link to ANO-001 and DRV-001 in the Issue Tracker",
        ],
        action_when_rejected: [
          "Mark FUQ-001 as not required — payroll spike resolved through alternative documentation",
          "Log resolution note in Issue Tracker",
        ],
        suggestion_prompt: "Add this question to the formal management question list with a 5-business-day response deadline.",
        target_recipient: "CFO / VP Finance — Meridian Industrial Solutions",
        target_channel: "Question List",
        priority: "Critical",
        status: "Pending",
      },
    },
    {
      question_id: "FUQ-002",
      question_text: "Please provide the AR aging schedule as of December 31, 2023, identifying any balances over 90 days, disputed invoices, or customer concentrations exceeding 10% of total AR.",
      priority: "High",
      target_audience: "Controller",
      linked_finding_id: "ANO-002",
      rationale: "AR increased $4.2M in Q4 2023. Aging detail is needed to assess collectability and determine whether a normalisation adjustment to working capital is warranted.",
      call_to_action: {
        title: "Send FUQ-002 to Controller",
        description: "Deliver question FUQ-002 requesting AR aging schedule as of Dec 31, 2023 to assess collectability of the $4.2M Q4 build-up.",
        impact: "Without this information, working capital analysis cannot be completed, blocking the purchase price adjustment recommendation.",
        action_when_approved: [
          "Add FUQ-002 to the management question list",
          "Flag as blocking for working capital section of diligence report",
          "Link to ANO-002 and DRV-002 in the Issue Tracker",
        ],
        action_when_rejected: [
          "Mark FUQ-002 as not required — AR confirmed collected post-period",
          "Update working capital analysis accordingly",
        ],
        suggestion_prompt: "Add this question to the management question list and flag it as blocking for the working capital analysis.",
        target_recipient: "Controller — Meridian Industrial Solutions",
        target_channel: "Question List",
        priority: "High",
        status: "Pending",
      },
    },
    {
      question_id: "FUQ-003",
      question_text: "What is the nature of the $650,000 credit recorded in Other Income (account 7800) in March 2023? Please provide supporting documentation including any settlement agreements, asset sale proceeds, or insurance claim details.",
      priority: "Medium",
      target_audience: "CFO",
      linked_finding_id: "ANO-004",
      rationale: "A one-time $650K credit with no prior account activity must be classified as non-recurring. Without documentation, this cannot be excluded from EBITDA with confidence.",
      call_to_action: {
        title: "Send FUQ-003 to CFO",
        description: "Deliver question FUQ-003 requesting documentation for the $650K Other Income credit in March 2023.",
        impact: "If non-recurring (likely), this reduces normalised LTM EBITDA by $650K — a ~4% reduction on estimated $16M EBITDA.",
        action_when_approved: [
          "Add FUQ-003 to the management question list",
          "Pre-classify as non-recurring QoE adjustment pending response",
          "Link to ANO-004 in the Issue Tracker",
        ],
        action_when_rejected: [
          "Mark FUQ-003 as not required — Other Income confirmed as recurring",
          "Retain $650K in normalised EBITDA",
        ],
        suggestion_prompt: "Add this question to the management question list requesting documentation for the $650K Other Income credit.",
        target_recipient: "CFO — Meridian Industrial Solutions",
        target_channel: "Question List",
        priority: "Medium",
        status: "Pending",
      },
    },
  ],
  issue_tracker: [
    {
      issue_id: "ISS-001",
      account_name: "Payroll Expense",
      account_code: "6100",
      period: "Jul 2023 – Sep 2023",
      severity: "Critical",
      status: "Open",
      driver_summary: "Possible reclassification from Direct Labour (6050) or one-time bonus accrual. $420K partial offset identified but $1.0M remains unexplained.",
      linked_finding_id: "ANO-001",
      call_to_action: {
        title: "Escalate ISS-001 for Senior Review",
        description: "Issue ISS-001 (Payroll Spike — $1.42M) is Critical and open. Escalate to senior analyst for review and prioritise in management question list.",
        impact: "Unresolved critical issues block signing off on the Quality of Earnings chapter of the diligence report.",
        action_when_approved: [
          "Set ISS-001 status to 'Under Review'",
          "Assign to senior analyst",
          "Escalation note added to diligence workpaper",
        ],
        action_when_rejected: [
          "Mark ISS-001 as 'Dismissed' with analyst note",
          "Log reason for dismissal in workpaper",
        ],
        suggestion_prompt: "Escalate this critical issue to senior review and set a resolution deadline.",
        target_recipient: "Senior Analyst / Engagement Manager",
        target_channel: "Issue Tracker",
        priority: "Critical",
        status: "Pending",
      },
    },
    {
      issue_id: "ISS-002",
      account_name: "Accounts Receivable",
      account_code: "1200",
      period: "Oct 2023 – Dec 2023",
      severity: "High",
      status: "Open",
      driver_summary: "DSO increased from 28 to 51 days. Possible large single-customer sale with extended terms. Collection confirmation needed.",
      linked_finding_id: "ANO-002",
      call_to_action: {
        title: "Request AR Aging and Confirm Collection",
        description: "Issue ISS-002 (AR Build-Up — $4.2M) is High priority. Obtain aging schedule and confirm post-period collection before closing the issue.",
        impact: "If not collected, working capital target adjustment of $1–2M may be required in the purchase agreement.",
        action_when_approved: [
          "Set ISS-002 status to 'Under Review'",
          "Add FUQ-002 to management question list",
          "Flag for working capital peg analysis",
        ],
        action_when_rejected: [
          "Mark ISS-002 as 'Resolved' — collection confirmed",
          "Update working capital analysis",
        ],
        suggestion_prompt: "Move this issue to 'Under Review' and request the AR aging schedule.",
        target_recipient: "Controller — Meridian Industrial Solutions",
        target_channel: "Issue Tracker",
        priority: "High",
        status: "Pending",
      },
    },
    {
      issue_id: "ISS-003",
      account_name: "Cost of Goods Sold",
      account_code: "5000",
      period: "Nov 2023 – Dec 2023",
      severity: "High",
      status: "Open",
      driver_summary: "COGS spike $870K with flat revenue. Possible strategic pre-buy of raw materials or vendor price increase. Gross margin compressed 9pp.",
      linked_finding_id: "ANO-003",
      call_to_action: {
        title: "Determine Recurring vs Non-Recurring Nature of COGS Spike",
        description: "Issue ISS-003 (COGS Spike — $870K) requires classification as recurring or non-recurring. Request purchase orders and vendor invoices.",
        impact: "If non-recurring, normalised gross margin restores to 38% and LTM EBITDA increases ~$870K. If recurring, structural margin compression must be disclosed.",
        action_when_approved: [
          "Set ISS-003 status to 'Under Review'",
          "Add FUQ to management question list requesting purchase orders",
          "Flag for gross margin normalisation analysis",
        ],
        action_when_rejected: [
          "Mark ISS-003 as 'Dismissed' — COGS increase confirmed as structural",
          "Retain in normalised EBITDA — no adjustment",
        ],
        suggestion_prompt: "Move to 'Under Review' and add a question requesting purchase orders for the COGS spike.",
        target_recipient: "VP Operations — Meridian Industrial Solutions",
        target_channel: "Issue Tracker",
        priority: "High",
        status: "Pending",
      },
    },
    {
      issue_id: "ISS-004",
      account_name: "Other Income",
      account_code: "7800",
      period: "Mar 2023",
      severity: "Medium",
      status: "Open",
      driver_summary: "One-time $650K credit with no prior account history. Likely non-recurring gain — insurance, asset sale, or settlement.",
      linked_finding_id: "ANO-004",
      call_to_action: {
        title: "Classify Other Income Credit as Non-Recurring",
        description: "Issue ISS-004 ($650K Other Income) is Medium priority pending documentation. Pre-classify as non-recurring and request confirmation from management.",
        impact: "Reduces normalised LTM EBITDA by $650K (~4% on estimated $16M EBITDA).",
        action_when_approved: [
          "Set ISS-004 status to 'Under Review'",
          "Pre-apply QoE normalisation adjustment of -$650K",
          "Add FUQ-003 to management question list",
        ],
        action_when_rejected: [
          "Mark ISS-004 as 'Resolved' — confirmed recurring income",
          "Remove normalisation adjustment",
        ],
        suggestion_prompt: "Pre-classify as non-recurring and add to the QoE normalisation schedule.",
        target_recipient: "CFO — Meridian Industrial Solutions",
        target_channel: "Issue Tracker",
        priority: "Medium",
        status: "Pending",
      },
    },
  ],
  metadata: {
    source_files: ["Meridian_TB_2021-2023.xlsx", "Meridian_Workpapers_Q3Q4_2023.docx"],
    period_range: "Jan 2021 – Dec 2023",
    processed_at: "2026-05-24",
    session_id: "sample-session-meridian-001",
    agent_version: "1.0.0",
  },
};
